old_sound_rabbit_mq:
    connections:
        default:
            url: '%env(RABBITMQ_URL)%'
            lazy: true
    producers:
        # use 'old_sound_rabbit_mq.task_producer' service to send data.
        receive_data:
            connection:       default
            exchange_options: { name: 'receive_data', type: direct }
#        task:
#            connection:       default
#            exchange_options: { name: 'task', type: direct }
    consumers:
        receive_data:
            connection:       default
            exchange_options:  { name: 'receive_data', type: direct }
            queue_options:     { name: 'receive_data' }
            callback:         App\Consumer\ReceiveDataService
#        task:
#            connection:       default
#            exchange_options: { name: 'task', type: direct }
#            queue_options:    { name: 'task'}
#            callback:         App\Consumer\TaskConsumer
